//
// Created by USER on 15/01/2023.
//

#ifndef AUTHENTICATION_SYSTEM_CASCADE_OBJECT_DETECTOR_H
#define AUTHENTICATION_SYSTEM_CASCADE_OBJECT_DETECTOR_H


class Cascade_Object_Detector {

};


#endif //AUTHENTICATION_SYSTEM_CASCADE_OBJECT_DETECTOR_H
